# -*- coding: utf-8 -*-
"""Voucher exchange history.

One record per point -> voucher exchange. Generated by
/voucher-diskon/exchange/<tier_id> controller endpoint.

State machine:
  draft  -> issued (voucher code generated, points deducted)
  issued -> used   (admin marked voucher as redeemed by customer)
  issued -> void   (admin voided, points returned to partner)
"""
import random
import string

from odoo import _, api, fields, models


class LoyaltyExchange(models.Model):
    _name = 'wl.loyalty.exchange'
    _description = 'Warung Lakku Loyalty Point Exchange'
    _order = 'create_date DESC'
    _rec_name = 'voucher_code'

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='cascade',
        index=True,
    )
    voucher_tier_id = fields.Many2one(
        'wl.loyalty.voucher.tier',
        string='Voucher Tier',
        required=True,
        ondelete='restrict',
    )
    voucher_value = fields.Monetary(
        string='Voucher Value (Rp)',
        related='voucher_tier_id.voucher_value',
        store=True,
        readonly=True,
    )
    point_cost = fields.Integer(
        string='Points Spent',
        related='voucher_tier_id.point_cost',
        store=True,
        readonly=True,
    )
    voucher_code = fields.Char(
        string='Voucher Code',
        copy=False,
        readonly=True,
        help="Generated plain-text code. Customer uses this code at "
             "checkout (admin applies manually for now).",
    )
    state = fields.Selection([
        ('draft', 'Draft'),
        ('issued', 'Issued'),
        ('used', 'Used'),
        ('void', 'Voided'),
    ], string='State', default='draft', required=True, index=True)
    currency_id = fields.Many2one(
        'res.currency',
        default=lambda self: self.env.company.currency_id,
    )
    notes = fields.Text(string='Notes')

    def _generate_voucher_code(self):
        """Generate a 10-char voucher code, format: WL-XXXX-XXXX."""
        alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
        for _attempt in range(20):
            code = 'WL-' + '-'.join(
                ''.join(random.choices(alphabet, k=4))
                for _ in range(2))
            if not self.search_count([('voucher_code', '=', code)]):
                return code
        return 'WL-' + ''.join(random.choices(string.digits, k=8))

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for rec in records:
            if not rec.voucher_code:
                rec.voucher_code = rec._generate_voucher_code()
            if rec.state == 'draft':
                rec.state = 'issued'
            # Deduct points from partner (defensive; the controller
            # already checks balance and writes points before create)
            if rec.partner_id.loyalty_points < rec.point_cost:
                # Should not happen — controller guards — but just in case
                continue
            rec.partner_id.sudo().write({
                'loyalty_points':
                    rec.partner_id.loyalty_points - rec.point_cost,
            })
        return records

    def action_mark_used(self):
        for rec in self:
            if rec.state != 'issued':
                continue
            rec.state = 'used'

    def action_void(self):
        """Void the exchange and refund the points."""
        for rec in self:
            if rec.state not in ('issued', 'used'):
                continue
            rec.partner_id.sudo().write({
                'loyalty_points':
                    rec.partner_id.loyalty_points + rec.point_cost,
            })
            rec.state = 'void'
